import sys

sys.path.append("C:\\Users\\steph\\Desktop\\freecaddotnet\\.conda\\Library\\Mod\\Web")
sys.path.append("C:\\Users\\steph\\Desktop\\freecaddotnet\\.conda\\Library\\Mod\\Tux")
sys.path.append("C:\\Users\\steph\\Desktop\\freecaddotnet\\.conda\\Library\\Mod\\Test")
sys.path.append("C:\\Users\\steph\\Desktop\\freecaddotnet\\.conda\\Library\\Mod\\TechDraw")
sys.path.append("C:\\Users\\steph\\Desktop\\freecaddotnet\\.conda\\Library\\Mod\\Surface")
sys.path.append("C:\\Users\\steph\\Desktop\\freecaddotnet\\.conda\\Library\\Mod\\Start")
sys.path.append("C:\\Users\\steph\\Desktop\\freecaddotnet\\.conda\\Library\\Mod\\Spreadsheet")
sys.path.append("C:\\Users\\steph\\Desktop\\freecaddotnet\\.conda\\Library\\Mod\\Sketcher")
sys.path.append("C:\\Users\\steph\\Desktop\\freecaddotnet\\.conda\\Library\\Mod\\Show")
sys.path.append("C:\\Users\\steph\\Desktop\\freecaddotnet\\.conda\\Library\\Mod\\Robot")
sys.path.append("C:\\Users\\steph\\Desktop\\freecaddotnet\\.conda\\Library\\Mod\\ReverseEngineering")
sys.path.append("C:\\Users\\steph\\Desktop\\freecaddotnet\\.conda\\Library\\Mod\\Points")
sys.path.append("C:\\Users\\steph\\Desktop\\freecaddotnet\\.conda\\Library\\Mod\\Plot")
sys.path.append("C:\\Users\\steph\\Desktop\\freecaddotnet\\.conda\\Library\\Mod\\Path")
sys.path.append("C:\\Users\\steph\\Desktop\\freecaddotnet\\.conda\\Library\\Mod\\PartDesign")
sys.path.append("C:\\Users\\steph\\Desktop\\freecaddotnet\\.conda\\Library\\Mod\\Part")
sys.path.append("C:\\Users\\steph\\Desktop\\freecaddotnet\\.conda\\Library\\Mod\\OpenSCAD")
sys.path.append("C:\\Users\\steph\\Desktop\\freecaddotnet\\.conda\\Library\\Mod\\MeshPart")
sys.path.append("C:\\Users\\steph\\Desktop\\freecaddotnet\\.conda\\Library\\Mod\\Mesh")
sys.path.append("C:\\Users\\steph\\Desktop\\freecaddotnet\\.conda\\Library\\Mod\\Measure")
sys.path.append("C:\\Users\\steph\\Desktop\\freecaddotnet\\.conda\\Library\\Mod\\Material")
sys.path.append("C:\\Users\\steph\\Desktop\\freecaddotnet\\.conda\\Library\\Mod\\Inspection")
sys.path.append("C:\\Users\\steph\\Desktop\\freecaddotnet\\.conda\\Library\\Mod\\Import")
sys.path.append("C:\\Users\\steph\\Desktop\\freecaddotnet\\.conda\\Library\\Mod\\Idf")
sys.path.append("C:\\Users\\steph\\Desktop\\freecaddotnet\\.conda\\Library\\Mod\\Fem")
sys.path.append("C:\\Users\\steph\\Desktop\\freecaddotnet\\.conda\\Library\\Mod\\Draft")
sys.path.append("C:\\Users\\steph\\Desktop\\freecaddotnet\\.conda\\Library\\Mod\\Arch")
sys.path.append("C:\\Users\\steph\\Desktop\\freecaddotnet\\.conda\\Library\\Mod\\AddonManager")
sys.path.append("C:\\Users\\steph\\Desktop\\freecaddotnet\\.conda\\Library\\Mod")
sys.path.append("C:\\Users\\steph\\Desktop\\freecaddotnet\\.conda\\Library\\lib")
sys.path.append("C:\\Users\\steph\\Desktop\\freecaddotnet\\.conda\\Library\\Ext")
sys.path.append("C:\\Users\\steph\\Desktop\\freecaddotnet\\.conda\\Library\\bin")
sys.path.append("C:\\Users\\steph\\Desktop\\freecaddotnet\\.conda\\Library\\Macro")

# Now import FreeCAD
#import FreeCAD as App

# You can now use the FreeCAD API
#doc = App.newDocument()
import freecad
import FreeCAD as App